In [42]:
#Question 1

import numpy as np
x=np.random.rand(10,1)
print("Formed Matrix Is \n",x)

print("Mean Of The Above Matrix Is =",np.sum(x)/len(x))


#Second Method
print("Mean Of The Above Matrix Is =",np.mean(x))


Formed Matrix Is 
 [[0.37241407]
 [0.59029328]
 [0.64831771]
 [0.11046474]
 [0.42935075]
 [0.8870795 ]
 [0.79518368]
 [0.07208599]
 [0.08029116]
 [0.27993096]]
Mean Of The Above Matrix Is = 0.4265411845006476
Mean Of The Above Matrix Is = 0.4265411845006476


In [46]:
#Question 2

x=np.random.rand(20,1)
print("Formed Matrix Is \n",x)

print("Variance of the formed matrix is =",np.var(x))


print("Standard deviation of the formed matrix is =",np.std(x))
#Second Method For standard deviation
print("Variance of the formed matrix is =",np.sqrt(np.var(x)))


Formed Matrix Is 
 [[0.1409732 ]
 [0.84186587]
 [0.85906325]
 [0.41658577]
 [0.55850218]
 [0.09645293]
 [0.08715437]
 [0.56882939]
 [0.14197133]
 [0.98238417]
 [0.2305642 ]
 [0.82243769]
 [0.27892079]
 [0.20084056]
 [0.82335289]
 [0.26691669]
 [0.79109434]
 [0.05456388]
 [0.67632445]
 [0.59525798]]
Variance of the formed matrix is = 0.09325528285191242
Standard deviation of the formed matrix is = 0.30537727952798394
Variance of the formed matrix is = 0.30537727952798394


In [55]:
#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

x=np.dot(A,B)
print("Matrix Formed After Multiplication\n",x)


print("Sum Of Newly Formed Matrix = ",np.sum(x))

Matrix Formed After Multiplication
 [[6.72651227 4.84913827 4.58116487 4.38459616 5.75823312 3.54372222
  4.16093958 5.13740415 4.35080272 3.35452359 5.46211282 5.75166862
  4.70493583 5.85646727 4.335563   3.93610602 4.84341805 5.78188585
  4.64422661 4.43921183 5.05663346 4.79358711 5.89442712 4.31401835
  6.09664053]
 [6.7705851  5.42333731 5.67169236 4.82975075 6.5340101  4.46942411
  4.86857922 6.13381888 5.0784848  4.01846264 6.6180269  6.10159214
  5.85995022 6.7446588  4.76323243 5.0927509  5.2515221  6.22357254
  6.4527293  4.69093364 4.76673466 4.96257931 6.60683306 5.94410369
  6.17389851]
 [7.51985385 5.15130918 6.86850381 5.71478906 7.7745985  4.99192893
  6.50609637 7.44617206 5.41161757 4.65242371 6.90315916 6.22099371
  5.40783395 7.26929239 5.7156369  6.20819442 6.53759125 7.83328543
  6.26388248 5.61299116 6.0777635  6.05778602 7.11983107 6.16249999
  7.93026986]
 [5.19510849 3.4239325  4.5113995  3.65965133 4.59470644 3.45380216
  3.8557756  4.03320243 3.6924047  3.2

In [84]:
#Question 4
#f(x)=1 / (1 + exp(-x)) 
from math import exp
y=np.random.rand(10,1)
print(y)
l=[]
for i in y:
    l.append(1/(1+exp(-(i))))
    
print("\n\n\nAfter performing given function")
print(np.array(l).reshape(10,1))    

[[0.92065213]
 [0.41306738]
 [0.20974384]
 [0.35570468]
 [0.88816119]
 [0.64611894]
 [0.62900412]
 [0.37754222]
 [0.93865497]
 [0.86094524]]



After performing given function
[[0.71517496]
 [0.60182315]
 [0.55224457]
 [0.58800026]
 [0.70851056]
 [0.65613534]
 [0.65226362]
 [0.59328018]
 [0.71882789]
 [0.7028581 ]]
